const data = [
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
  {
    bondImage: "#",
    bondName: "RAIDER-ETH SLP",
    payoutAssetImage: "#",
    payoutAssetTokenPrice: "$0.0346",
    discount: "-3.65%",
    tbv: "$60,000",
    action: "Bond",
  },
];
export default data;
//https://images.app.goo.gl/xyjpnGnVCZgbQpcFA
